spring:
  application:
    name: user-center
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/zhang
  session:
    timeout: 86400 #一天多少秒，表示session的生存周期
    store-type: redis # 设置服务器保存session的类型时候，可以选择redis
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER #为了兼容2.6以上的springboot

  redis:
    host: 192.168.226.132
    port: 6379
    password: 123456
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s
  jackson:
    default-property-inclusion: non_null # JSON处理时忽略非空字段
server:
  port: 8080
  servlet:
    context-path: /api #后端地址全体加了一个api
    session:
      cookie:
        domain: localhost  # 表示在这种域名下，会种下cookie
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false #设置不开启下划线和驼峰的转化。
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
knife4j:
  enable: true
  openapi:
    title: Knife4j官方文档
    description: 这是一个官方接口
    email: xiaoymin@foxmail.com
    concat: zhang
    url: https://docs.xiaominfo.com
    version: v4.0
    license: Apache 2.0
    license-url: https://stackoverflow.com/
    terms-of-service-url: https://stackoverflow.com/
    group:
      test1:
        group-name: default
        api-rule: package
        api-rule-resources:
          - com.zhang.usercenter.controller